---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: npm install --legacy-peer-deps

      - name: Deploy
        run: |
          git config --global user.name 'Cosmina Nicu'
          git config --global user.email 'cosminanicu@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run deploy